//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUSER")]
    public interface IUSER {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUSER/signUp")]
        void signUp(string _ssn, string _name, string _password, string _age, string _gender, string _weight);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUSER/signUp")]
        System.Threading.Tasks.Task signUpAsync(string _ssn, string _name, string _password, string _age, string _gender, string _weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUSER/signIn", ReplyAction="http://tempuri.org/IUSER/signInResponse")]
        string signIn(string _name, string _password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUSER/signIn", ReplyAction="http://tempuri.org/IUSER/signInResponse")]
        System.Threading.Tasks.Task<string> signInAsync(string _name, string _password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUSER/findUser", ReplyAction="http://tempuri.org/IUSER/findUserResponse")]
        string[] findUser(string _ssn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUSER/findUser", ReplyAction="http://tempuri.org/IUSER/findUserResponse")]
        System.Threading.Tasks.Task<string[]> findUserAsync(string _ssn);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUSER/updateUser")]
        void updateUser(string _ssn, string _name, string _password, string _age, string _gender, string _weight);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUSER/updateUser")]
        System.Threading.Tasks.Task updateUserAsync(string _ssn, string _name, string _password, string _age, string _gender, string _weight);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUSERChannel : WindowsFormsApplication1.ServiceReference1.IUSER, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class USERClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.IUSER>, WindowsFormsApplication1.ServiceReference1.IUSER {
        
        public USERClient() {
        }
        
        public USERClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public USERClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public USERClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public USERClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void signUp(string _ssn, string _name, string _password, string _age, string _gender, string _weight) {
            base.Channel.signUp(_ssn, _name, _password, _age, _gender, _weight);
        }
        
        public System.Threading.Tasks.Task signUpAsync(string _ssn, string _name, string _password, string _age, string _gender, string _weight) {
            return base.Channel.signUpAsync(_ssn, _name, _password, _age, _gender, _weight);
        }
        
        public string signIn(string _name, string _password) {
            return base.Channel.signIn(_name, _password);
        }
        
        public System.Threading.Tasks.Task<string> signInAsync(string _name, string _password) {
            return base.Channel.signInAsync(_name, _password);
        }
        
        public string[] findUser(string _ssn) {
            return base.Channel.findUser(_ssn);
        }
        
        public System.Threading.Tasks.Task<string[]> findUserAsync(string _ssn) {
            return base.Channel.findUserAsync(_ssn);
        }
        
        public void updateUser(string _ssn, string _name, string _password, string _age, string _gender, string _weight) {
            base.Channel.updateUser(_ssn, _name, _password, _age, _gender, _weight);
        }
        
        public System.Threading.Tasks.Task updateUserAsync(string _ssn, string _name, string _password, string _age, string _gender, string _weight) {
            return base.Channel.updateUserAsync(_ssn, _name, _password, _age, _gender, _weight);
        }
    }
}
